version: '3'

services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: ${DOCKER_REGISTRY}/dockerwebproxy_proxy
    ports:
      - "80:80"
      - "443:443"
      - "3000"
    volumes:
      - /opt/data/dockerwebproxy_letencrypt:/etc/letsencrypt
    networks:
      webproxy-network:
        aliases:
          - webproxy-proxy

  watcher:
    build:
      context: .
      dockerfile: Dockerfile-watcher
    image: ${DOCKER_REGISTRY}/dockerwebproxy_watcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      webproxy-network:
        aliases:
          - webproxy-watcher
    depends_on:
      - proxy
    deploy:
      mode: global

networks:
  webproxy-network:
    external: true
