version: '3'

services:

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/data/certificates:/opt/data/certificates
    networks:
      - webproxy-network
    restart: always

networks:
  webproxy-network:
    external: true
