version: '3'

services:

  nginx:
    build: .
    image: ${DOCKER_REGISTRY}/dockerwebproxy_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/data/certificates:/opt/data/certificates
    networks:
      - webproxy-network
    restart: always
    environment:
      - "constraint:webproxy==true"
    deploy:
      mode: global

networks:
  webproxy-network:
    external: true
