version: '3'

services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/data/certificates:/opt/data/certificates
    networks:
      - webproxy-network

  watcher:
    build:
      context: .
      dockerfile: Dockerfile-watcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webproxy-network

networks:
  webproxy-network:
    external: true
